### ISSUE TITLE
「NDLOCR（ver.2.1）の実行例」を使用して横書きの書籍をOCR処理した場合、埋め込まれたOCRテキストの配置が不正確なPDFが生成される

### ISSUE THREAD

**Issue by likibp** [nakamura196/000_tools#1]
### 概要

ノートブック「NDLOCR（ver.2.1）の実行例」を使用して横書きの書籍をOCR処理し、生成されるPDFを確認したところ、埋め込まれたOCRテキストの配置が不正確であることを確認しました。さらに、PDFのプロパティによれば、使用している日本語フォントのエンコーディングが縦書き用のフォントエンコーディング`UniJIS-UCS-V`になっていました。なお、PDFから文字をコピー＆ペーストすると、OCRの認識自体は正確であることが確認しました。
### 再現手順

1. ノートブックの「単一の画像ファイルのURLを指定する場合」セクションに移動。
2. URL欄に「[https://dl.ndl.go.jp/api/iiif/1175815/R0000033/full/full/0/default.jpg](https://dl.ndl.go.jp/api/iiif/1175815/R0000033/full/full/0/default.jpg)」を入力し、実行。（テスト対象[: 国立国会図書館デジタルコレクション『鉄道震害調査書』](https://dl.ndl.go.jp/pid/1175815)）
3. 生成されるPDFフォルダ内の`*_text.pdf`を開く。

### 期待される動作

OCR対象の書籍の文章が縦書きか横書きかを判別して、認識結果を適切な文書方向でPDFに埋め込みをする。
今回のテストの場合、OCRの認識結果が赤色の横書きテキストとして表示される。また、PDFのプロパティによると、使用している日本語フォントのエンコーディングが`UniJIS-UCS-H`である。

### 実際の動作

OCRの認識結果が一見表示されていないように見える。しかしながら、PDFを拡大して中心部分を確認すると、各行に小さな縦書きテキストとして認識結果が表示されている。PDFのプロパティからは、使用されている日本語フォントのエンコーディングが`UniJIS-UCS-V`として確認される。

**Comment by nakamura196** [comment]
ご指摘ありがとうございます。確認の上、修正いたします。

**Comment by nakamura196** [comment]
添付画像のようにPDF出力を修正しました。

![image](https://github.com/nakamura196/000_tools/assets/5351691/d8f315e2-7526-41a3-98e7-01e2148dcf29)

**Comment by likibp** [comment]
対応ありがとうございます。
縦書き・横書きとも正常に配置できたことを確認いたしました。ただ、修正にともない、*_text.pdfでない方の透明テキスト版PDFが行ごとに青い四角で囲まれて表示されるようになりました。こちらも対応お願いします。

**Comment by nakamura196** [comment]
不具合について申し訳ありませんでした。修正いたしました。

**Comment by likibp** [comment]
対応ありがとうございます。修正確認いたしましたのでクローズします。
